name: Deploy Portfolio (Production + Preview)

on:
  push:
    branches:
      - '**'   # trigger on all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set deployment folder
        id: vars
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "DIR=." >> $GITHUB_ENV
          else
            echo "DIR=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ${{ env.DIR }}
